# Use a separate pre-commit config that runs only when Rust dependencies
# are added, removed or modified.
repos:
-   repo: local
    hooks:
      - id: audit
        name: audit
        language: system
        files: 'Cargo\.lock|Cargo\.toml$'
        entry: cargo audit
        pass_filenames: false

default_language_version:
    python: python3
